use_frameworks!

platform :ios, '10.0'

target 'SwiftNetworkLayer_Example' do
  pod 'SwiftNetworkLayer', :path => '../'

  target 'SwiftNetworkLayer_Tests' do
    inherit! :search_paths

    
  end
end
